In [2]:
import torch
import torch.nn as nn

In [3]:
model = nn.Linear(10, 1)

In [ ]:
x = torch.zeros(10)
model(x)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


tensor([-0.0952], grad_fn=<ViewBackward0>)

In [10]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, output_dim) -> None:
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, output_dim)

    def forward(self, x):
        return nn.functional.sigmoid(self.linear(x))
    
model = LinearClassifier(10, 1)
x = torch.zeros(10)
model(x)

tensor([0.4612], grad_fn=<SigmoidBackward0>)

In [12]:
class LinearClassifier(torch.nn.Module):
    def __init__(self, input_dim, n_classes) -> None:
        super().__init__()
        self.linear = torch.nn.Linear(input_dim, n_classes)

    def forward(self, x):
        return nn.functional.softmax(self.linear(x), dim=-1)
    
model = LinearClassifier(10, 4)
x = torch.rand(20,10)
model(x)

tensor([[0.3344, 0.1210, 0.2126, 0.3321],
        [0.4743, 0.1605, 0.1974, 0.1679],
        [0.3098, 0.1343, 0.2858, 0.2702],
        [0.3580, 0.1929, 0.2146, 0.2344],
        [0.4264, 0.1238, 0.2100, 0.2397],
        [0.3809, 0.1608, 0.2237, 0.2347],
        [0.3112, 0.1413, 0.2240, 0.3234],
        [0.4376, 0.1317, 0.1919, 0.2387],
        [0.4306, 0.1578, 0.2364, 0.1752],
        [0.3250, 0.1874, 0.2370, 0.2506],
        [0.4280, 0.1412, 0.1778, 0.2530],
        [0.4161, 0.1876, 0.1999, 0.1964],
        [0.4408, 0.1539, 0.2143, 0.1910],
        [0.4320, 0.1742, 0.1987, 0.1950],
        [0.4735, 0.1132, 0.1874, 0.2259],
        [0.3588, 0.1554, 0.1984, 0.2874],
        [0.3471, 0.1626, 0.2443, 0.2460],
        [0.3528, 0.1814, 0.2305, 0.2353],
        [0.4365, 0.1605, 0.1565, 0.2465],
        [0.3824, 0.1588, 0.2506, 0.2082]], grad_fn=<SoftmaxBackward0>)