In [2]:
import torch



In [3]:
a = torch.tensor([1,2,3])


In [4]:
b = torch.rand([3,3,3], dtype=torch.float32)
print(b)

tensor([[[0.1663, 0.8348, 0.7823],
         [0.2412, 0.7862, 0.0835],
         [0.8450, 0.2141, 0.4053]],

        [[0.8121, 0.6263, 0.4646],
         [0.6900, 0.3530, 0.5891],
         [0.5382, 0.0620, 0.3753]],

        [[0.4203, 0.5521, 0.7760],
         [0.8438, 0.5625, 0.8396],
         [0.3237, 0.3861, 0.9227]]])


In [5]:
from PIL import Image
import numpy as np

img = Image.open("./flowers/flowers-102/jpg/image_00001.jpg")
c = torch.as_tensor(np.array(img))
print(c.shape)

torch.Size([500, 591, 3])


In [6]:
a = torch.arange(10)
b = torch.ones(10)
print(f'{a + b = }')

a + b = tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])


In [7]:
a = torch.rand(1_000_000)
b = torch.rand(1_000_000)
%timeit c = a + b

297 μs ± 24.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
a = torch.rand(2,3,4)
print(a)
print(a.permute(1,2,0))


tensor([[[0.3151, 0.9537, 0.4113, 0.6528],
         [0.6088, 0.6566, 0.7498, 0.0191],
         [0.0124, 0.7538, 0.7249, 0.0538]],

        [[0.2829, 0.3729, 0.5808, 0.4990],
         [0.8833, 0.2716, 0.3813, 0.8831],
         [0.6659, 0.2632, 0.6418, 0.6112]]])
tensor([[[0.3151, 0.2829],
         [0.9537, 0.3729],
         [0.4113, 0.5808],
         [0.6528, 0.4990]],

        [[0.6088, 0.8833],
         [0.6566, 0.2716],
         [0.7498, 0.3813],
         [0.0191, 0.8831]],

        [[0.0124, 0.6659],
         [0.7538, 0.2632],
         [0.7249, 0.6418],
         [0.0538, 0.6112]]])


In [ ]:
a = torch.arange(6).view(3,2,1,1)
print(a.squeeze(0).shape)

torch.Size([3, 2, 1])
